apiVersion: v1
kind: Service
metadata:
  labels:
    app: atlas-broker
  name: atlas-broker
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: atlas-broker
  sessionAffinity: None
  type: ClusterIP
